# Default values for wallabag.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

wallabag:
  domainName: http://localhost:8080
  fosUserConfirmation: false
  fosUserRegistration: false
  secret:
    create: true
    name: ""
  email:
    enabled: false
    fromEmail: wallabag@example.com
    host: 127.0.0.1
    password: "~"
    username: "~"
  database:
    # -- The database driver. One of `sqlite` or `postgresql`.
    driver: sqlite
    # -- The database host.
    host: wallabag
    # -- The database name.
    name: wallabag
    # -- The database port.
    port: ""
    # -- The database password.
    password: wallabag
    # -- The database username.
    username: wallabag
  importWorkers:
    # -- Enable import workers for importing backups and data.
    enabled: false
    # -- Apply resources to all import workers
    resources: {}
    wallabag_v1:
      # -- Enable the wallabag_v1 importer.
      enabled: false
      # resouces: {}
    wallabag_v2:
      # -- Enable the wallabag_v2 importer.
      enabled: false
      # resouces: {}
  # -- Symfony secret for cryptographic seed. This should be a randomly generated string. Leave blank for a random value.
  wallabagSecret: ""

postgresql:
  # -- Enable installation of postgresql subchart. See [bitnami/postgresql](https://github.com/bitnami/charts/tree/main/bitnami/postgresql/)
  enabled: false

redis:
  enabled: false
  replica:
    replicaCount: 0

  master:
    persistence:
      enabled: false


replicaCount: 1
podDisruptionBudget:
  enabled: false
  spec:
    minAvailable: 1

image:
  repository: wallabag/wallabag
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 8080
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
