{{- if .Values.wallabag.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallabag.fullname" . }}
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.wallabag.email.enabled }}
  email-from-email: {{ .Values.wallabag.email.fromEmail | b64enc }}
  email-mailer-host: {{ .Values.wallabag.email.host | b64enc }}
  email-mailer-password: {{ .Values.wallabag.email.password | b64enc }}
  email-mailer-username: {{ .Values.wallabag.email.username | b64enc }}
  {{- end }}

  database-name: {{ .Values.wallabag.database.name | b64enc }}
  database-password: {{ .Values.wallabag.database.password | b64enc }}
  database-username: {{ .Values.wallabag.database.username | b64enc }}
  {{- if eq .Values.wallabag.database.driver "postgresql" }}
  database-host: {{ printf "%s-postgresql" (include "wallabag.fullname" .)  | b64enc }}
  database-port: {{ .Values.wallabag.database.port | default "5432" | toString | b64enc }}
  {{- end }}

  {{- if .Values.redis.enabled }}
  redis-password: {{ .Values.redis.auth.password | b64enc }}
  redis-host: {{ printf "%s-redis-master" (include "wallabag.fullname" .)  | b64enc }}
  {{- end }}

  # https://itnext.io/manage-auto-generated-secrets-in-your-helm-charts-5aee48ba6918
  # When secrets are not set in values, retrieve them from existing state or autogenerate them.
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := lookup "v1" "Secret" .Release.Namespace (include "wallabag.fullname" .) | default dict }}
  {{- $secretData := get $secretObj "data" | default dict }}

  # set $secret to existing secret data or generate a random one when not exists
  {{- $secret := get $secretData "wallabag-secret" | default (randAlphaNum 32 | b64enc) }}
  wallabag-secret: {{ .Values.wallabag.wallabagSecret | default $secret | b64enc }}
{{- end }}
