---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallabag.fullname" . }}
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.wallabag.email.enabled }}
  SYMFONY__ENV__FROM_EMAIL: {{ .Values.wallabag.email.password }}
  SYMFONY__ENV__MAILER_HOST: {{ .Values.wallabag.email.password }}
  SYMFONY__ENV__MAILER_PASSWORD: {{ .Values.wallabag.email.password }}
  SYMFONY__ENV__MAILER_USER: {{ .Values.wallabag.email.user }}
  {{- end }}

  {{- if eq .Values.wallabag.database.driver "postgresql" }}
  POSTGRES_USER: {{ "postgres" | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | b64enc }}
  SYMFONY__ENV__DATABASE_DRIVER: {{ "pdo_pgsql" | b64enc }}
  SYMFONY__ENV__DATABASE_HOST: {{ printf "%s-postgresql" (include "wallabag.fullname" .)  | b64enc }}
  SYMFONY__ENV__DATABASE_PORT: {{ .Values.wallabag.database.port | default "5432" | toString | b64enc }}
  {{- else }}
  SYMFONY__ENV__DATABASE_DRIVER: {{ "pdo_sqlite" | b64enc }}
  {{- end }}
  SYMFONY__ENV__DATABASE_NAME: {{ .Values.wallabag.database.name | b64enc }}
  SYMFONY__ENV__DATABASE_USER: {{ .Values.wallabag.database.user | b64enc }}
  SYMFONY__ENV__DATABASE_PASSWORD: {{ .Values.wallabag.database.password | b64enc }}

  {{- if .Values.redis.enabled }}
  SYMFONY__ENV__REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc }}
  SYMFONY__ENV__REDIS_HOST: {{ printf "%s-redis-master" (include "wallabag.fullname" .)  | b64enc }}
  {{- end }}

  # https://itnext.io/manage-auto-generated-secrets-in-your-helm-charts-5aee48ba6918
  # When secrets are not set in values, retrieve them from existing state or autogenerate them.
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := lookup "v1" "Secret" .Release.Namespace (include "wallabag.fullname" .) | default dict }}
  {{- $secretData := get $secretObj "data" | default dict }}

  # set $secret to existing secret data or generate a random one when not exists
  {{- $secret := get $secretData "SYMFONY__ENV__SECRET" | default (randAlphaNum 32 | b64enc) }}
  SYMFONY__ENV__SECRET: {{ .Values.wallabag.secret | default $secret | b64enc }}
