---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallabag.fullname" . }}
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.wallabag.database.driver "postgres" }}
  databaseDriver: {{ "pdo_postgres" | b64enc }}
  {{- else }}
  databaseDriver: {{ "pdo_sqlite" | b64enc }}
  {{- end }}
  databaseHost: {{ .Values.wallabag.database.host | b64enc }}
  databaseName: {{ .Values.wallabag.database.name | b64enc }}
  databaseUser: {{ .Values.wallabag.database.user | b64enc }}
  databasePort: {{ .Values.wallabag.database.port | toString | b64enc }}
  databasePassword: {{ .Values.wallabag.database.password | b64enc }}
